# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication,QWidget


class Ui_MMK_system(object):
    def setupUi(self, MMK_system):
        MMK_system.setObjectName("MMK_system")
        MMK_system.resize(300, 400)
        self.gridLayoutWidget = QtWidgets.QWidget(MMK_system)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 210, 211, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(MMK_system)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 310, 231, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)

        self.retranslateUi(MMK_system)
        QtCore.QMetaObject.connectSlotsByName(MMK_system)

    def retranslateUi(self, MMK_system):
        _translate = QtCore.QCoreApplication.translate
        MMK_system.setWindowTitle(_translate("MMK_system", "Form"))
        self.label.setText(_translate("MMK_system", "账号:"))
        self.label_2.setText(_translate("MMK_system", "密码:"))
        self.pushButton_2.setText(_translate("MMK_system", "注册"))
        self.pushButton.setText(_translate("MMK_system", "登录"))

if __name__ == '__main__':
    app = QApplication(sys.argv)
    gui = Ui_MMK_system(QWidget)
    gui.show()
    sys.exit(app.exec_())
